### ISSUE TITLE
项目自我推荐

### ISSUE THREAD

**Issue by chenboshuo** [XaufeComputerTechnologyClub/XAUFE-COURSE-RESOURCE#1]
我这里有一些不错的项目，但是以目前的目录结构不知道加在哪里，你看一下是否有应用价值

## Latex 模板系列
-   [建模国赛模板](https://github.com/chenboshuo/cumcm_template)
-   [建模美赛模板](https://github.com/chenboshuo/mcm_template)
-   [latex slide 模板](https://github.com/chenboshuo/myslide_template)
      这个加上logo可以当学校的万能slide 
      ![logo](https://user-images.githubusercontent.com/43953268/159142294-0bb0942c-7333-4919-962e-451b518bb904.png)

-   [毕业设计模板](https://github.com/chenboshuo/XAUFE_thesis_template)

**Comment by everrwsr** [comment]
已经将你的项目自荐加入readme，感谢你为我们开辟了一个新栏目😉
